import type { PlayerProfile } from './schema'

export const PLAYER_PROFILES: PlayerProfile[] = [
  {
    id: 'pierre',
    displayName: 'Pierre',
    archetype: 'loose-passif calling station',
    summary:
      'Call tout le temps, paie trop pour voir, tres difficile a bluffer, value evidente contre lui.',
    targetStats: {
      vpip: [48, 62],
      pfr: [5, 10],
      limp: [25, 40],
      coldCall: [18, 32],
      threeBet: [0, 2],
      fourBet: [0, 1],
      cbetFlop: [25, 40],
      cbetTurn: [15, 30],
      cbetRiver: [5, 15],
      bluff: [0, 4],
      heroCall: [70, 90],
      overbet: [0, 5],
      preflopJamAbove35bb: [0, 0.1],
    },
    sizingStyle: 'passif_irrationnel',
    tableTalkStyle: 'relaxed',
    decisionTempoMultiplier: 1.12,
    quirks: {
      irrationalCalls: true,
      showdownCurious: true,
      stickyPairs: true,
    },
    specificRules: [
      'limp/call beaucoup',
      'paie trop avec top pair, middle pair, draws, hauteur parfois',
      'bluffe presque jamais',
      'fold difficilement face a petits ou moyens sizings',
      'peut payer des gros sizings par curiosite ou attachement a sa main',
      'si grosse aggression de sa part river, range plus forte que la moyenne',
    ],
  },
  {
    id: 'eric',
    displayName: 'Eric',
    archetype: 'agressif optimiste',
    summary:
      'Agressif, optimiste, surestime la force de ses raises et de ses mains. Peut mettre de la pression, peut aussi s emballer.',
    targetStats: {
      vpip: [28, 40],
      pfr: [18, 28],
      limp: [5, 15],
      coldCall: [8, 18],
      threeBet: [4, 9],
      fourBet: [1, 3],
      cbetFlop: [55, 70],
      cbetTurn: [35, 55],
      cbetRiver: [15, 30],
      bluff: [10, 20],
      heroCall: [35, 55],
      overbet: [5, 12],
      preflopJamAbove35bb: [0, 0.5],
    },
    emotionalProfile: {
      tiltSensitivity: 'medium',
      revengeFactor: 'medium',
    },
    sizingStyle: 'volatile_aggressif',
    tableTalkStyle: 'taunting',
    decisionTempoMultiplier: 0.92,
    quirks: {
      optimisticFoldEquity: true,
    },
    specificRules: [
      'attaque la faiblesse percue',
      'peut surjouer top pair ou overpair moyenne',
      'peut faire des gros sizings non all-in',
      'peut bluffer mais se decourage face a resistance credible',
      'plus aggro quand il se sent dominant',
    ],
  },
  {
    id: 'eric_b',
    displayName: 'Eric B',
    archetype: 'suiveur fou irrationnel',
    summary:
      'Tres irrationnel, suit trop, discipline faible, quasiment jamais en bluff construit. A value plus qu a bluff.',
    targetStats: {
      vpip: [45, 65],
      pfr: [3, 8],
      limp: [30, 50],
      coldCall: [20, 35],
      threeBet: [0, 2],
      fourBet: [0, 1],
      cbetFlop: [15, 30],
      cbetTurn: [10, 20],
      cbetRiver: [3, 10],
      bluff: [0, 2],
      heroCall: [60, 85],
      overbet: [0, 6],
      preflopJamAbove35bb: [0, 0.1],
    },
    sizingStyle: 'random_passif',
    tableTalkStyle: 'relaxed',
    decisionTempoMultiplier: 1.04,
    quirks: {
      irrationalCalls: true,
      showdownCurious: true,
      stickyPairs: true,
    },
    specificRules: [
      'suit trop meme avec des mains dominees',
      'quasi jamais de bluff intentionnel',
      'peut payer des sizings absurdes',
      'commet des erreurs de pot odds sans le savoir',
      'a modeliser comme tres collant, pas comme agressif',
    ],
  },
  {
    id: 'gilles',
    displayName: 'Gilles',
    archetype: 'serre passif',
    summary:
      'Serre-passif. Quand il entre serieusement dans un pot, il faut le respecter. Quelques bluffs opportunistes sur boards neutres.',
    targetStats: {
      vpip: [12, 20],
      pfr: [7, 12],
      limp: [5, 15],
      coldCall: [5, 12],
      threeBet: [1, 3],
      fourBet: [0, 1],
      cbetFlop: [35, 50],
      cbetTurn: [20, 35],
      cbetRiver: [8, 18],
      bluff: [5, 12],
      heroCall: [15, 30],
      overbet: [0, 5],
      preflopJamAbove35bb: [0, 0.1],
    },
    emotionalProfile: {
      riskAversion: 'medium',
    },
    sizingStyle: 'face_up_serre',
    tableTalkStyle: 'calm',
    decisionTempoMultiplier: 1.08,
    quirks: {
      valueHeavyRaises: true,
    },
    specificRules: [
      'presence dans un gros pot = danger',
      'raise fort rarement mais plus souvent en value',
      'bluffs surtout sur textures seches et credibles',
      'pas de folie gratuite',
    ],
  },
  {
    id: 'david',
    displayName: 'David',
    archetype: 'serre standard lisible',
    summary:
      'Plus proche d un jeu propre / standard, mais lisible. Peut etre exploite sur les mismatches board/range ou les lignes bizarres.',
    targetStats: {
      vpip: [17, 24],
      pfr: [13, 18],
      limp: [0, 8],
      coldCall: [5, 12],
      threeBet: [4, 7],
      fourBet: [1, 2],
      cbetFlop: [55, 70],
      cbetTurn: [35, 50],
      cbetRiver: [15, 25],
      bluff: [8, 15],
      heroCall: [20, 35],
      overbet: [0, 6],
      preflopJamAbove35bb: [0, 0.2],
    },
    sizingStyle: 'standard_plus_propre',
    tableTalkStyle: 'quiet',
    decisionTempoMultiplier: 0.96,
    quirks: {
      cleanPressure: true,
    },
    specificRules: [
      'plus coherent que la moyenne de la table',
      'moins de limp',
      'sizings plus standards',
      'peut trop raconter sa main',
      'reagit moins bien aux lines tres irrationnelles',
    ],
  },
  {
    id: 'fabrice',
    displayName: 'Fabrice',
    archetype: 'agressif calculateur',
    summary:
      'Le plus propre/agressif-calculateur du groupe. Peu de leaks grossiers. Evite d en faire un bot fou.',
    targetStats: {
      vpip: [22, 30],
      pfr: [18, 24],
      limp: [0, 6],
      coldCall: [5, 12],
      threeBet: [6, 10],
      fourBet: [2, 4],
      cbetFlop: [55, 70],
      cbetTurn: [40, 55],
      cbetRiver: [20, 32],
      bluff: [10, 18],
      heroCall: [20, 35],
      overbet: [3, 10],
      preflopJamAbove35bb: [0, 0.3],
    },
    sizingStyle: 'pression_propre',
    tableTalkStyle: 'quiet',
    decisionTempoMultiplier: 0.88,
    quirks: {
      cleanPressure: true,
    },
    specificRules: [
      'met de la pression mieux que les autres',
      'moins de calls idiots',
      'moins bluffable',
      'pas un nit, pas un kamikaze',
      'ne pas lui donner des spews gratuits',
    ],
  },
  {
    id: 'martin',
    displayName: 'Martin',
    archetype: 'agressif kamikaze',
    summary:
      'Agressif, joue pour l adrenaline, peut surjouer, peut spew, peut mettre des gros sizings et des overbets, surtout quand il s ennuie ou apres un coup emotionnel.',
    targetStats: {
      vpip: [35, 50],
      pfr: [24, 35],
      limp: [0, 10],
      coldCall: [5, 15],
      threeBet: [8, 16],
      fourBet: [4, 9],
      cbetFlop: [60, 80],
      cbetTurn: [45, 65],
      cbetRiver: [20, 40],
      bluff: [20, 35],
      heroCall: [20, 40],
      overbet: [10, 22],
      preflopJamAbove35bb: [0.5, 2.5],
    },
    emotionalProfile: {
      tiltSensitivity: 'high',
      revengeFactor: 'high',
      boredomLeak: 'high',
    },
    sizingStyle: 'overbet_heavy_kamikaze',
    tableTalkStyle: 'reactive',
    decisionTempoMultiplier: 0.78,
    quirks: {
      kamikazeBursts: true,
      optimisticFoldEquity: true,
    },
    specificRules: [
      'peut mettre une vraie pression',
      'plus susceptible que les autres aux gros coups emotionnels',
      'capable de 3-bet/4-bet plus loose',
      'peut overbluff',
      'mais ne doit pas shove deep a chaque orbite',
    ],
  },
  {
    id: 'renaud',
    displayName: 'Renaud',
    archetype: 'serre avec mains fetiches',
    summary:
      'Plutot serre, mais attachement irrationnel a certaines mains fetiches. Peut payer des overbets douteux avec ses mains preferees.',
    targetStats: {
      vpip: [18, 28],
      pfr: [10, 16],
      limp: [5, 15],
      coldCall: [8, 16],
      threeBet: [2, 5],
      fourBet: [0, 2],
      cbetFlop: [35, 55],
      cbetTurn: [20, 40],
      cbetRiver: [10, 20],
      bluff: [3, 10],
      heroCall: [40, 65],
      overbet: [0, 6],
      preflopJamAbove35bb: [0, 0.2],
    },
    sizingStyle: 'serre_biaise',
    tableTalkStyle: 'calm',
    decisionTempoMultiplier: 1,
    quirks: {
      favoriteHands: ['A4o', 'K4o', 'J3s'],
      favoriteHandsNotes: 'TODO_MATCH_REAL_TABLE',
      showdownCurious: true,
    },
    specificRules: [
      'profil serre globalement',
      'mais deviation forte quand il a une main fetiche',
      'peut trop s accrocher a certains combos',
      'ajoute un champ favoriteHands configurable avec TODO_MATCH_REAL_TABLE',
    ],
  },
  {
    id: 'pascal',
    displayName: 'Pascal',
    archetype: 'serre craintif',
    summary:
      'Tight, prudent, peur de la relance et du gros pot. Cible naturelle pour la pression. Bluffe peu.',
    targetStats: {
      vpip: [14, 22],
      pfr: [8, 12],
      limp: [5, 15],
      coldCall: [5, 12],
      threeBet: [1, 3],
      fourBet: [0, 1],
      cbetFlop: [35, 55],
      cbetTurn: [20, 35],
      cbetRiver: [5, 15],
      bluff: [0, 6],
      heroCall: [10, 25],
      overbet: [0, 3],
      preflopJamAbove35bb: [0, 0.1],
    },
    emotionalProfile: {
      riskAversion: 'high',
    },
    sizingStyle: 'scared_money',
    tableTalkStyle: 'quiet',
    decisionTempoMultiplier: 1.06,
    quirks: {
      scaredMoney: true,
    },
    specificRules: [
      'overfold face a l agression',
      'n aime pas etre relance',
      'se protege trop',
      'peu de bluffs credibles',
      'joue trop petit ou abandonne',
    ],
  },
]

export const PLAYER_PROFILES_BY_ID = Object.fromEntries(
  PLAYER_PROFILES.map((profile) => [profile.id, profile]),
) satisfies Record<string, PlayerProfile>
