import type { PlayerProfile } from './schema'

export const PLAYER_PROFILES: PlayerProfile[] = [
  {
    id: 'pierre',
    displayName: 'Pierre',
    archetype: 'loose-passif calling station',
    summary:
      'Call tout le temps, paie trop pour voir, tres difficile a bluffer, value evidente contre lui.',
    targetStats: {
      vpip: [48, 62],
      pfr: [5, 10],
      limp: [25, 40],
      coldCall: [18, 32],
      threeBet: [0, 2],
      fourBet: [0, 1],
      cbetFlop: [25, 40],
      cbetTurn: [15, 30],
      cbetRiver: [5, 15],
      bluff: [0, 4],
      heroCall: [70, 90],
      overbet: [0, 5],
      preflopJamAbove35bb: [0, 0.1],
    },
    sizingStyle: 'passif_irrationnel',
    tableTalkStyle: 'relaxed',
    decisionTempoMultiplier: 1.12,
    quirks: {
      irrationalCalls: true,
      showdownCurious: true,
      stickyPairs: true,
    },
    specificRules: [
      'limp/call beaucoup',
      'paie trop avec top pair, middle pair, draws, hauteur parfois',
      'bluffe presque jamais',
      'fold difficilement face a petits ou moyens sizings',
      'peut payer des gros sizings par curiosite ou attachement a sa main',
      'si grosse aggression de sa part river, range plus forte que la moyenne',
    ],
  },
  {
    id: 'eric_b',
    displayName: 'Eric B',
    archetype: 'agressif optimiste',
    summary:
      'Agressif, optimiste, surestime la force de ses raises et de ses mains. Peut mettre de la pression, peut aussi s emballer.',
    targetStats: {
      vpip: [28, 40],
      pfr: [18, 28],
      limp: [5, 15],
      coldCall: [8, 18],
      threeBet: [4, 9],
      fourBet: [1, 3],
      cbetFlop: [55, 70],
      cbetTurn: [35, 55],
      cbetRiver: [15, 30],
      bluff: [10, 20],
      heroCall: [35, 55],
      overbet: [5, 12],
      preflopJamAbove35bb: [0, 0.5],
    },
    emotionalProfile: {
      tiltSensitivity: 'medium',
      revengeFactor: 'medium',
    },
    sizingStyle: 'volatile_aggressif',
    tableTalkStyle: 'taunting',
    decisionTempoMultiplier: 0.92,
    quirks: {
      optimisticFoldEquity: true,
    },
    specificRules: [
      'attaque la faiblesse percue',
      'peut surjouer top pair ou overpair moyenne',
      'peut faire des gros sizings non all-in',
      'peut bluffer mais se decourage face a resistance credible',
      'plus aggro quand il se sent dominant',
    ],
  },
  {
    id: 'gilles',
    displayName: 'Jésus',
    archetype: 'degen preflop any two',
    summary:
      'Pas tight du tout. Pense que 35o vaut AA tant qu on ne connait pas le flop. Entre beaucoup trop large avant le flop, puis reajuste surtout apres avoir vu la texture.',
    targetStats: {
      vpip: [55, 75],
      pfr: [8, 18],
      limp: [25, 45],
      coldCall: [25, 45],
      threeBet: [2, 6],
      fourBet: [0, 1],
      cbetFlop: [35, 55],
      cbetTurn: [18, 35],
      cbetRiver: [8, 22],
      bluff: [8, 18],
      heroCall: [35, 60],
      overbet: [0, 8],
      preflopJamAbove35bb: [0, 0.1],
    },
    emotionalProfile: {
      boredomLeak: 'high',
    },
    sizingStyle: 'passif_irrationnel',
    tableTalkStyle: 'reactive',
    decisionTempoMultiplier: 0.9,
    quirks: {
      irrationalCalls: true,
      showdownCurious: true,
    },
    specificRules: [
      'avant le flop, peut traiter des mains tres faibles comme jouables',
      '35o peut lui sembler equivalent a une premium tant que le flop n est pas vu',
      'call beaucoup trop large preflop',
      'ne pas interpreter son entree preflop comme un signe de force',
      'reajuste davantage apres le flop selon la texture',
    ],
  },
  {
    id: 'david',
    displayName: 'David',
    archetype: 'serre standard lisible',
    summary:
      'Plus proche d un jeu propre / standard, mais lisible. Peut etre exploite sur les mismatches board/range ou les lignes bizarres.',
    targetStats: {
      vpip: [17, 24],
      pfr: [13, 18],
      limp: [0, 8],
      coldCall: [5, 12],
      threeBet: [4, 7],
      fourBet: [1, 2],
      cbetFlop: [55, 70],
      cbetTurn: [35, 50],
      cbetRiver: [15, 25],
      bluff: [8, 15],
      heroCall: [20, 35],
      overbet: [0, 6],
      preflopJamAbove35bb: [0, 0.2],
    },
    sizingStyle: 'standard_plus_propre',
    tableTalkStyle: 'quiet',
    decisionTempoMultiplier: 0.96,
    quirks: {
      cleanPressure: true,
    },
    specificRules: [
      'plus coherent que la moyenne de la table',
      'moins de limp',
      'sizings plus standards',
      'peut trop raconter sa main',
      'reagit moins bien aux lines tres irrationnelles',
    ],
  },
  {
    id: 'fabrice',
    displayName: 'Fabrice',
    archetype: 'agressif calculateur',
    summary:
      'Le plus propre/agressif-calculateur du groupe. Peu de leaks grossiers. Evite d en faire un bot fou.',
    targetStats: {
      vpip: [22, 30],
      pfr: [18, 24],
      limp: [0, 6],
      coldCall: [5, 12],
      threeBet: [6, 10],
      fourBet: [2, 4],
      cbetFlop: [55, 70],
      cbetTurn: [40, 55],
      cbetRiver: [20, 32],
      bluff: [10, 18],
      heroCall: [20, 35],
      overbet: [3, 10],
      preflopJamAbove35bb: [0, 0.3],
    },
    sizingStyle: 'pression_propre',
    tableTalkStyle: 'quiet',
    decisionTempoMultiplier: 0.88,
    quirks: {
      cleanPressure: true,
    },
    specificRules: [
      'met de la pression mieux que les autres',
      'moins de calls idiots',
      'moins bluffable',
      'pas un nit, pas un kamikaze',
      'ne pas lui donner des spews gratuits',
    ],
  },
  {
    id: 'martin',
    displayName: 'Martin',
    archetype: 'agressif kamikaze',
    summary:
      'Agressif, joue pour l adrenaline, peut surjouer, peut spew, peut mettre des gros sizings et des overbets, surtout quand il s ennuie ou apres un coup emotionnel.',
    targetStats: {
      vpip: [35, 50],
      pfr: [24, 35],
      limp: [0, 10],
      coldCall: [5, 15],
      threeBet: [8, 16],
      fourBet: [4, 9],
      cbetFlop: [60, 80],
      cbetTurn: [45, 65],
      cbetRiver: [20, 40],
      bluff: [20, 35],
      heroCall: [20, 40],
      overbet: [10, 22],
      preflopJamAbove35bb: [0.5, 2.5],
    },
    emotionalProfile: {
      tiltSensitivity: 'high',
      revengeFactor: 'high',
      boredomLeak: 'high',
    },
    sizingStyle: 'overbet_heavy_kamikaze',
    tableTalkStyle: 'reactive',
    decisionTempoMultiplier: 0.78,
    quirks: {
      kamikazeBursts: true,
      optimisticFoldEquity: true,
    },
    specificRules: [
      'peut mettre une vraie pression',
      'plus susceptible que les autres aux gros coups emotionnels',
      'capable de 3-bet/4-bet plus loose',
      'peut overbluff',
      'mais ne doit pas shove deep a chaque orbite',
    ],
  },
  {
    id: 'renaud',
    displayName: 'Renaud',
    archetype: 'serre avec mains fetiches',
    summary:
      'Plutot serre, mais attachement irrationnel a certaines mains fetiches. Peut payer des overbets douteux avec ses mains preferees.',
    targetStats: {
      vpip: [18, 28],
      pfr: [10, 16],
      limp: [5, 15],
      coldCall: [8, 16],
      threeBet: [2, 5],
      fourBet: [0, 2],
      cbetFlop: [35, 55],
      cbetTurn: [20, 40],
      cbetRiver: [10, 20],
      bluff: [3, 10],
      heroCall: [40, 65],
      overbet: [0, 6],
      preflopJamAbove35bb: [0, 0.2],
    },
    sizingStyle: 'serre_biaise',
    tableTalkStyle: 'calm',
    decisionTempoMultiplier: 1,
    quirks: {
      favoriteHands: ['A4o', 'K4o', 'J3s'],
      favoriteHandsNotes: 'TODO_MATCH_REAL_TABLE',
      showdownCurious: true,
    },
    specificRules: [
      'profil serre globalement',
      'mais deviation forte quand il a une main fetiche',
      'peut trop s accrocher a certains combos',
      'ajoute un champ favoriteHands configurable avec TODO_MATCH_REAL_TABLE',
    ],
  },
  {
    id: 'pascal',
    displayName: 'Pascal',
    archetype: 'serre craintif',
    summary:
      'Tight, prudent, peur de la relance et du gros pot. Cible naturelle pour la pression. Bluffe peu.',
    targetStats: {
      vpip: [14, 22],
      pfr: [8, 12],
      limp: [5, 15],
      coldCall: [5, 12],
      threeBet: [1, 3],
      fourBet: [0, 1],
      cbetFlop: [35, 55],
      cbetTurn: [20, 35],
      cbetRiver: [5, 15],
      bluff: [0, 6],
      heroCall: [10, 25],
      overbet: [0, 3],
      preflopJamAbove35bb: [0, 0.1],
    },
    emotionalProfile: {
      riskAversion: 'high',
    },
    sizingStyle: 'scared_money',
    tableTalkStyle: 'quiet',
    decisionTempoMultiplier: 1.06,
    quirks: {
      scaredMoney: true,
    },
    specificRules: [
      'overfold face a l agression',
      'n aime pas etre relance',
      'se protege trop',
      'peu de bluffs credibles',
      'joue trop petit ou abandonne',
    ],
  },
  {
    id: 'pascal_2',
    displayName: 'Pascal 2',
    archetype: 'recreatif qui veut vibrer',
    summary:
      'Joueur recreatif venu pour vibrer. Evite les mains vraiment pourries, mais peut jouer large, miser fort et bluffer souvent.',
    targetStats: {
      vpip: [30, 45],
      pfr: [16, 26],
      limp: [8, 20],
      coldCall: [12, 24],
      threeBet: [3, 8],
      fourBet: [0, 2],
      cbetFlop: [60, 78],
      cbetTurn: [45, 65],
      cbetRiver: [25, 45],
      bluff: [18, 32],
      heroCall: [30, 50],
      overbet: [6, 15],
      preflopJamAbove35bb: [0, 0.5],
    },
    emotionalProfile: {
      tiltSensitivity: 'medium',
      boredomLeak: 'medium',
    },
    sizingStyle: 'volatile_aggressif',
    tableTalkStyle: 'reactive',
    decisionTempoMultiplier: 0.95,
    quirks: {
      optimisticFoldEquity: true,
    },
    specificRules: [
      'cherche les spots qui font vibrer',
      'n aime pas trop entrer avec des mains vraiment pourries',
      'peut quand meme jouer assez large avec des mains jouables',
      'mise beaucoup quand il sent de la fold equity',
      'bluffe souvent, sans etre en bluff automatique',
      'peut mettre des gros sizings non all-in pour faire passer',
    ],
  },
  {
    id: 'philippe',
    displayName: 'Philippe',
    archetype: 'tres serre-agressif lisible',
    summary:
      'Joue tres peu de mains. Quand il touche, il mise ou relance fort; ses grosses agressions sont tres souvent en value et donc assez lisibles.',
    targetStats: {
      vpip: [10, 17],
      pfr: [8, 14],
      limp: [0, 3],
      coldCall: [2, 7],
      threeBet: [2, 5],
      fourBet: [0, 1],
      cbetFlop: [45, 60],
      cbetTurn: [35, 50],
      cbetRiver: [25, 40],
      bluff: [0, 4],
      heroCall: [12, 25],
      overbet: [6, 14],
      preflopJamAbove35bb: [0, 0.2],
    },
    emotionalProfile: {
      riskAversion: 'medium',
    },
    sizingStyle: 'face_up_serre',
    tableTalkStyle: 'quiet',
    decisionTempoMultiplier: 1.08,
    quirks: {
      valueHeavyRaises: true,
    },
    specificRules: [
      'entre dans tres peu de pots et limpe rarement',
      'quand il touche le board, mise ou relance volontiers et plutot fort',
      'ses gros sizings sont tres majoritairement en value',
      'bluffe presque jamais et abandonne souvent quand il a manque',
      'une aggression soudaine de sa part indique une range tres forte',
      'privilegier les gros sizings non all-in avec ses mains fortes',
    ],
  },
  {
    id: 'gerard',
    displayName: 'Gérard',
    archetype: 'ultra loose-agressif overbluffeur',
    summary:
      'Entre avec presque tout, mise tres souvent et tres gros meme avec peu de force. Peut largement overbluffer et son aggression represente mal la force reelle de sa main.',
    targetStats: {
      vpip: [68, 85],
      pfr: [38, 58],
      limp: [5, 16],
      coldCall: [20, 38],
      threeBet: [12, 24],
      fourBet: [4, 10],
      cbetFlop: [72, 90],
      cbetTurn: [58, 78],
      cbetRiver: [40, 65],
      bluff: [32, 50],
      heroCall: [35, 60],
      overbet: [24, 42],
      preflopJamAbove35bb: [0, 0.2],
    },
    emotionalProfile: {
      tiltSensitivity: 'high',
      revengeFactor: 'high',
      boredomLeak: 'high',
    },
    sizingStyle: 'overbet_heavy_kamikaze',
    tableTalkStyle: 'taunting',
    decisionTempoMultiplier: 0.72,
    quirks: {
      kamikazeBursts: true,
      optimisticFoldEquity: true,
    },
    specificRules: [
      'entre preflop avec presque n importe quelles deux cartes',
      'ouvre, relance et 3-bet beaucoup trop large',
      'mise souvent tres gros avec une force faible ou marginale',
      'peut multiplier les barrels et overbluffer',
      'son gros sizing ne doit pas etre interprete automatiquement comme de la force',
      'privilegier les tres gros sizings non all-in plutot que les shoves deep',
    ],
  },
  {
    id: 'arnaud',
    displayName: 'Arnaud',
    archetype: 'exploitant analytique adaptatif',
    summary:
      'Ne joue pas une charte fixe: main + prix + position + profondeur + profil + image + dynamique = decision. Cherche les spots EV+, value les joueurs qui paient trop, bluffe rarement mais peut utiliser un bluff montre comme investissement d image.',
    targetStats: {
      vpip: [22, 32],
      pfr: [16, 24],
      limp: [0, 8],
      coldCall: [6, 14],
      threeBet: [4, 8],
      fourBet: [1, 3],
      cbetFlop: [48, 68],
      cbetTurn: [32, 52],
      cbetRiver: [14, 28],
      bluff: [8, 18],
      heroCall: [28, 45],
      overbet: [2, 8],
      preflopJamAbove35bb: [0, 0.2],
    },
    sizingStyle: 'standard_plus_propre',
    tableTalkStyle: 'calm',
    decisionTempoMultiplier: 0.98,
    quirks: {
      cleanPressure: true,
    },
    specificRules: [
      'evalue chaque main comme un investissement, pas comme une force absolue',
      'entre dans un coup si le prix, la position, la profondeur et les profils rendent le spot rentable',
      'elargit au cutoff/bouton et resserre hors position ou face a un prix trop cher',
      'privilegie les mains qui dominent les ranges adverses ou peuvent faire un gros jeu cache bien paye',
      'evite les mains jolies mais dominees, surtout offsuit et hors position',
      'contre les calling stations: reduit les bluffs et value plus cher quand il pense etre devant',
      'contre les passifs: donne beaucoup de credit aux mises/relances soudaines',
      'peut miser avec equite sans pur bluff: fold equity + possibilite d ameliorer + controle du pot',
      'utilise quelques bluffs visibles comme investissement d image, pas comme tendance loose permanente',
      'apres un bluff montre, reduit les bluffs immediats contre les joueurs dont la fold equity a chute',
      'adapte les sizings au train de call: trop petit attire tout le monde, trop gros ne garde parfois que mieux',
      'l option/straddle est une arme d initiative mais augmente la variance si la profondeur effective baisse',
      'ne decide pas l option seulement selon sa main ou la profondeur: la position des relanceurs naturels est decisive',
      'si le relanceur principal est immediatement a sa gauche, l option est plus controlable car le prix reel apparait vite',
      'si le relanceur principal est a sa droite, l option devient plus dangereuse: il peut poster 2K puis subir open, relance ou surrelance avec beaucoup de mains forcees au fold',
      'avec des familles de mains jouables/speculatives comme paires moyennes, suited connectors/gappers, Ax suited, broadways ou near-broadways, peut completer tres volontiers si le prix final est connu et excellent',
      'exemples non exhaustifs: 99, 88, 77, JT, QT, Q9, J9; la logique vient surtout des implied odds, de la position et du prix',
      'ces memes familles deviennent souvent un fold face a une sequence open plus 3-bet creee par un relanceur a sa droite: force representee haute, prix instable, reverse implied odds et profondeur insuffisante pour rentabiliser proprement',
    ],
  },
  {
    id: 'bruno',
    displayName: 'Bruno',
    archetype: 'inconnu complet',
    summary:
      'Nouveau joueur inconnu pour la session du 2026-06-09. Modele neutre, sans leak affirme tant qu aucune main observee ne confirme une tendance.',
    targetStats: {
      vpip: [20, 32],
      pfr: [10, 20],
      limp: [5, 18],
      coldCall: [8, 18],
      threeBet: [2, 6],
      fourBet: [0, 2],
      cbetFlop: [40, 60],
      cbetTurn: [25, 45],
      cbetRiver: [10, 22],
      bluff: [5, 13],
      heroCall: [25, 45],
      overbet: [0, 5],
      preflopJamAbove35bb: [0, 0.2],
    },
    sizingStyle: 'standard_plus_propre',
    tableTalkStyle: 'quiet',
    decisionTempoMultiplier: 1.02,
    specificRules: [
      'profil inconnu',
      'eviter les hypotheses fortes',
      'mettre a jour des qu on observe VPIP, agressivite, calls et sizings',
    ],
  },
  {
    id: 'guillaume',
    displayName: 'Guillaume',
    archetype: 'inconnu prudent par defaut',
    summary:
      'Joueur ajoute pour la session du 2026-06-09. Profil par defaut prudent/neutre en attendant observation: ne pas lui attribuer de leak fort sans preuve.',
    targetStats: {
      vpip: [20, 32],
      pfr: [10, 18],
      limp: [6, 18],
      coldCall: [8, 18],
      threeBet: [2, 6],
      fourBet: [0, 2],
      cbetFlop: [38, 58],
      cbetTurn: [22, 42],
      cbetRiver: [8, 20],
      bluff: [4, 12],
      heroCall: [25, 45],
      overbet: [0, 5],
      preflopJamAbove35bb: [0, 0.2],
    },
    sizingStyle: 'standard_plus_propre',
    tableTalkStyle: 'quiet',
    decisionTempoMultiplier: 1,
    specificRules: [
      'profil inconnu pour le moment',
      'partir sur une range neutre et observer rapidement VPIP, limps, calls et sizings',
      'ne pas construire une strategie specifique contre lui avant signaux fiables',
    ],
  },
]

export const PLAYER_PROFILES_BY_ID = Object.fromEntries(
  PLAYER_PROFILES.map((profile) => [profile.id, profile]),
) satisfies Record<string, PlayerProfile>

export const SESSION_2026_06_09_PROFILE_IDS = [
  'eric_b',
  'gilles',
  'pierre',
  'david',
  'guillaume',
  'bruno',
  'pascal_2',
  'fabrice',
  'philippe',
  'gerard',
] as const

export const SESSION_2026_06_09_PROFILES = SESSION_2026_06_09_PROFILE_IDS.map((id) => PLAYER_PROFILES_BY_ID[id])

export const AFTERNOON_2026_07_11_PROFILE_IDS = [
  'gilles',
  'eric_b',
  'david',
  'philippe',
  'gerard',
  'pierre',
  'fabrice',
] as const
