import type { TableRules } from './schema'

export const REAL_TABLE_RULES: TableRules = {
  tableName: 'Session privee 2026-06-09',
  variant: 'texas-holdem-no-limit',
  mode: 'cash',
  maxSeats: 10,
  smallBlind: 500,
  bigBlind: 1_000,
  ante: 0,
  startingStack: 40_000,
  buyInDefault: 40_000,
  currencyLabel: 'MGA',
  rake: 0,
  botActionDelayMs: {
    min: 600,
    max: 1_800,
  },
  heroSeatIndex: 0,
  heroDisplayName: 'Arnaud',
  includeHero: true,
  fixedSeatOrder: [
    'hero',
    'eric_b',
    'pierre',
    'david',
    'guillaume',
    'bruno',
    'pascal_2',
    'fabrice',
    'philippe',
    'gerard',
  ],
  oddChipRule: 'first-left-of-dealer',
  blindProgression: 'static',
  straddle: {
    enabled: false,
    amount: 2_000,
    label: 'Option',
  },
  rebuy: {
    enabled: true,
    defaultAmount: 40_000,
    maxStackFraction: 0.5,
    availabilityRule: 'half-max-stack',
    notes: 'Recave au minimum a 40 000, jusqu a 50 % du plus gros stack de la table.',
    policy: 'auto-when-busted',
  },
}
